export type Category = 'Hombre' | 'Mujer' | 'Unisex'

export interface Product {
  id: string
  slug: string
  nombre: string
  marca: string
  categoria: Category
  descripcion: string
  notas_olfativas: string[]
  ml: number
  precio_referencial: number
  imagen: string
  link_whatsapp: string
}

export const WHATSAPP_NUMBER = '541160461248'

const wa = (nombre: string) =>
  `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(
    `Hola, me interesa obtener información sobre el perfume ${nombre}`
  )}`

const rawProducts: Omit<Product, 'slug'>[] = [
  { id: '1', nombre: 'Tharwah Gold', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Amaderado especiado, elegante y cálido. Salida fresca con especias suaves, corazón aromático y fondo ámbar amaderado con aire lujoso.', notas_olfativas: ['Amaderado', 'Especiado', 'Ámbar'], ml: 100, precio_referencial: 114999, imagen: '/perfumes/tharwah-gold.webp', link_whatsapp: wa('Tharwah Gold') },
  { id: '2', nombre: 'Asad Bourbon', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Vainillado especiado y licoroso. Dulce masculino con canela, cacao y maderas profundas tipo bourbon.', notas_olfativas: ['Vainilla', 'Especiado', 'Amaderado'], ml: 100, precio_referencial: 73999, imagen: '/perfumes/asad-bourbon.webp', link_whatsapp: wa('Asad Bourbon') },
  { id: '3', nombre: 'The Kingdom', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Ámbar dulce especiado. Sensación sofisticada y nocturna, con vainilla cremosa, especias y maderas cálidas.', notas_olfativas: ['Ámbar', 'Dulce', 'Especiado'], ml: 100, precio_referencial: 74999, imagen: '/perfumes/the-kingdom.webp', link_whatsapp: wa('The Kingdom') },
  { id: '4', nombre: 'Vintage Radio', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Aromático afrutado amaderado. Moderno, limpio y elegante con frutas suaves, lavanda y fondo cremoso.', notas_olfativas: ['Aromático', 'Frutal', 'Amaderado'], ml: 100, precio_referencial: 74999, imagen: '/perfumes/vintage-radio.webp', link_whatsapp: wa('Vintage Radio') },
  { id: '5', nombre: 'Her Confession', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Floral avainillado sensual. Dulce elegante con flores blancas, vainilla y almizcle suave.', notas_olfativas: ['Floral', 'Vainilla', 'Almizcado'], ml: 100, precio_referencial: 85999, imagen: '/perfumes/her-confession.webp', link_whatsapp: wa('Her Confession') },
  { id: '7', nombre: 'Asad Black', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Amaderado especiado intenso. Oscuro, masculino y seductor con pimienta, incienso y vainilla ahumada.', notas_olfativas: ['Amaderado', 'Especiado', 'Vainilla'], ml: 100, precio_referencial: 71999, imagen: '/perfumes/asad-black.webp', link_whatsapp: wa('Asad Black') },
  { id: '8', nombre: 'Fakhar Black', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Aromático fresco amaderado. Limpio, masculino y versátil con cítricos, lavanda y fondo moderno.', notas_olfativas: ['Aromático', 'Cítrico', 'Amaderado'], ml: 100, precio_referencial: 75999, imagen: '/perfumes/fakhar-black.webp', link_whatsapp: wa('Fakhar Black') },
  { id: '9', nombre: 'Eclaire', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Gourmand dulce cremoso. Caramelo, leche y vainilla con sensación de postre elegante.', notas_olfativas: ['Gourmand', 'Dulce', 'Vainilla'], ml: 100, precio_referencial: 71999, imagen: '/perfumes/eclaire.webp', link_whatsapp: wa('Eclaire') },
  { id: '10', nombre: 'Fakhar Rose', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Floral frutal femenino. Rosas suaves, frutas dulces y fondo delicadamente cremoso.', notas_olfativas: ['Floral', 'Frutal', 'Dulce'], ml: 100, precio_referencial: 75999, imagen: '/perfumes/fakhar-rose.webp', link_whatsapp: wa('Fakhar Rose') },
  { id: '11', nombre: 'Fakhar Platin', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Fresco metálico amaderado. Perfil limpio y elegante con cítricos brillantes y maderas suaves.', notas_olfativas: ['Cítrico', 'Amaderado', 'Almizcado'], ml: 100, precio_referencial: 75999, imagen: '/perfumes/fakhar-platin.webp', link_whatsapp: wa('Fakhar Platin') },
  { id: '12', nombre: 'Khamrah Qahwa', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Gourmand especiado cafetero. Café tostado, canela, vainilla y licor dulce oriental.', notas_olfativas: ['Café', 'Especiado', 'Vainilla'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/khamrah-qahwa.webp', link_whatsapp: wa('Khamrah Qahwa') },
  { id: '13', nombre: 'Khamrah', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Ámbar gourmand especiado. Dulce intenso con canela, dátiles, vainilla y toque licoroso.', notas_olfativas: ['Ámbar', 'Dulce', 'Vainilla'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/khamrah.webp', link_whatsapp: wa('Khamrah') },
  { id: '14', nombre: 'Fakhar Gold', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Dulce floral oriental. Elegante y luminoso con flores blancas, vainilla y almizcle.', notas_olfativas: ['Floral', 'Vainilla', 'Almizcado'], ml: 100, precio_referencial: 79999, imagen: '/perfumes/fakhar-gold.webp', link_whatsapp: wa('Fakhar Gold') },
  { id: '15', nombre: 'Yara Moi', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Cremoso floral almizclado. Dulce delicado con vainilla blanca y flores suaves.', notas_olfativas: ['Floral', 'Vainilla', 'Almizcado'], ml: 100, precio_referencial: 53999, imagen: '/perfumes/yara-moi.webp', link_whatsapp: wa('Yara Moi') },
  { id: '16', nombre: 'Yara Rosa', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Floral frutal, dulce y femenino. Salida fresca con notas tropicales, corazón floral delicado y fondo cremoso de vainilla con un aire suave y elegante.', notas_olfativas: ['Floral', 'Frutal', 'Vainilla'], ml: 100, precio_referencial: 56999, imagen: '/perfumes/yara-rosa.webp', link_whatsapp: wa('Yara Rosa') },
  { id: '17', nombre: 'Yara Tous', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Tropical mango cremoso. Dulce exótico con mango, coco y almizcle.', notas_olfativas: ['Frutal', 'Tropical', 'Almizcado'], ml: 100, precio_referencial: 53999, imagen: '/perfumes/yara-tous.webp', link_whatsapp: wa('Yara Tous') },
  { id: '18', nombre: 'Yara Candy', marca: 'LATTAFA', categoria: 'Mujer', descripcion: 'Gourmand caramelizado. Azucarado, divertido y juvenil con frutas dulces y vainilla.', notas_olfativas: ['Gourmand', 'Dulce', 'Frutal'], ml: 100, precio_referencial: 54999, imagen: '/perfumes/yara-candy.webp', link_whatsapp: wa('Yara Candy') },
  { id: '19', nombre: 'Honor & Glory', marca: 'LATTAFA', categoria: 'Hombre', descripcion: 'Dulce especiado ahumado. Piña caramelizada, vainilla y maderas intensas.', notas_olfativas: ['Especiado', 'Dulce', 'Ahumado'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/honor-and-glory.webp', link_whatsapp: wa('Honor & Glory') },
  { id: '20', nombre: 'Badee Al Oud Amethyst', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Oud rosado oriental. Rosa intensa, oud elegante y vainilla cálida.', notas_olfativas: ['Oud', 'Floral', 'Vainilla'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/badee-al-oud-amethyst.webp', link_whatsapp: wa('Badee Al Oud Amethyst') },
  { id: '21', nombre: 'Badee Al Oud Sublime', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Frutal oscuro amaderado. Ciruela, frutas negras y oud suave elegante.', notas_olfativas: ['Oud', 'Frutal', 'Amaderado'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/badee-al-oud-sublime.webp', link_whatsapp: wa('Badee Al Oud Sublime') },
  { id: '22', nombre: 'Delilah', marca: 'MAISON ALHAMBRA', categoria: 'Mujer', descripcion: 'Floral empolvado elegante. Rosa turca, peonías y vainilla suave femenina.', notas_olfativas: ['Floral', 'Empolvado', 'Vainilla'], ml: 100, precio_referencial: 79999, imagen: '/perfumes/delilah.webp', link_whatsapp: wa('Delilah') },
  { id: '23', nombre: 'Sceptre Malachite', marca: 'MAISON ALHAMBRA', categoria: 'Unisex', descripcion: 'Verde fresco amaderado. Cítrico elegante con notas verdes y fondo limpio.', notas_olfativas: ['Verde', 'Cítrico', 'Amaderado'], ml: 100, precio_referencial: 69999, imagen: '/perfumes/sceptre-malachite.webp', link_whatsapp: wa('Sceptre Malachite') },
  { id: '24', nombre: 'Philos Pura', marca: 'MAISON ALHAMBRA', categoria: 'Unisex', descripcion: 'Frutal almizclado tropical. Frutas jugosas, almizcle blanco y vainilla, muy cercano al estilo Erba Pura.', notas_olfativas: ['Frutal', 'Almizcado', 'Vainilla'], ml: 100, precio_referencial: 57999, imagen: '/perfumes/philos-pura.webp', link_whatsapp: wa('Philos Pura') },
  { id: '26', nombre: 'Salvo Elixir', marca: 'MAISON ALHAMBRA', categoria: 'Hombre', descripcion: 'Amaderado especiado potente. Lavanda, especias y vainilla oscura masculina.', notas_olfativas: ['Amaderado', 'Especiado', 'Vainilla'], ml: 60, precio_referencial: 49999, imagen: '/perfumes/salvo-elixir.webp', link_whatsapp: wa('Salvo Elixir') },
  { id: '27', nombre: 'Glacier pour Homme', marca: 'MAISON ALHAMBRA', categoria: 'Hombre', descripcion: 'Fresco acuático limpio. Refrescante, masculino y versátil con cítricos y maderas suaves.', notas_olfativas: ['Acuático', 'Cítrico', 'Amaderado'], ml: 100, precio_referencial: 47999, imagen: '/perfumes/glacier-pour-homme.webp', link_whatsapp: wa('Glacier pour Homme') },
  { id: '28', nombre: 'Watani Noir Al Wataniah', marca: 'AL WATANIAH', categoria: 'Hombre', descripcion: 'Oscuro oriental especiado. Misterioso y elegante con incienso, vainilla y maderas.', notas_olfativas: ['Oud', 'Especiado', 'Amaderado'], ml: 100, precio_referencial: 59999, imagen: '/perfumes/watani-noir-al-wataniah.webp', link_whatsapp: wa('Watani Noir Al Wataniah') },
  { id: '29', nombre: 'Durrat al Araoos', marca: 'AL WATANIAH', categoria: 'Mujer', descripcion: 'Floral dulce oriental. Femenino, delicado y elegante con flores blancas y vainilla.', notas_olfativas: ['Floral', 'Dulce', 'Vainilla'], ml: 100, precio_referencial: 73999, imagen: '/perfumes/durrat-al-araoos.webp', link_whatsapp: wa('Durrat al Araoos') },
  { id: '30', nombre: 'Ameerati Al Wataniah', marca: 'AL WATANIAH', categoria: 'Mujer', descripcion: 'Amaderado dulce árabe. Ámbar cálido, especias suaves y fondo sensual.', notas_olfativas: ['Ámbar', 'Amaderado', 'Especiado'], ml: 100, precio_referencial: 59999, imagen: '/perfumes/ameerati-al-wataniah.webp', link_whatsapp: wa('Ameerati Al Wataniah') },
  { id: '31', nombre: 'Ghala Al Wataniah', marca: 'AL WATANIAH', categoria: 'Mujer', descripcion: 'Oriental gourmand intenso. Dulce árabe profundo con caramelo, oud y vainilla.', notas_olfativas: ['Oud', 'Dulce', 'Vainilla'], ml: 100, precio_referencial: 51999, imagen: '/perfumes/ghala-al-wataniah.webp', link_whatsapp: wa('Ghala Al Wataniah') },
  { id: '32', nombre: 'Club De Nuit Iconic', marca: 'ARMAF', categoria: 'Hombre', descripcion: 'Cítrico amaderado elegante. Fresco azul moderno con pomelo, menta y maderas limpias.', notas_olfativas: ['Cítrico', 'Amaderado', 'Almizcado'], ml: 105, precio_referencial: 82999, imagen: '/perfumes/club-de-nuit-iconic.webp', link_whatsapp: wa('Club De Nuit Iconic') },
  { id: '33', nombre: 'Club the Nuit Intense Man', marca: 'ARMAF', categoria: 'Hombre', descripcion: 'Cítrico ahumado masculino. Limón, piña y fondo oscuro amaderado tipo Aventus.', notas_olfativas: ['Cítrico', 'Amaderado', 'Ahumado'], ml: 105, precio_referencial: 76999, imagen: '/perfumes/club-the-nuit-intense-man.webp', link_whatsapp: wa('Club the Nuit Intense Man') },
  { id: '34', nombre: 'Club De Nuit Urban Elixir', marca: 'ARMAF', categoria: 'Hombre', descripcion: 'Fresco especiado moderno. Mezcla entre frescura azul y fondo oscuro seductor.', notas_olfativas: ['Cítrico', 'Especiado', 'Amaderado'], ml: 105, precio_referencial: 74999, imagen: '/perfumes/club-de-nuit-urban-elixir.webp', link_whatsapp: wa('Club De Nuit Urban Elixir') },
  { id: '35', nombre: 'Odyssey Mandarin Sky', marca: 'ARMAF', categoria: 'Unisex', descripcion: 'Dulce cítrico gourmand. Mandarina brillante, caramelo y toque masculino moderno.', notas_olfativas: ['Cítrico', 'Dulce', 'Gourmand'], ml: 100, precio_referencial: 68999, imagen: '/perfumes/odyssey-mandarin-sky.webp', link_whatsapp: wa('Odyssey Mandarin Sky') },
  { id: '36', nombre: 'Hawas Ice', marca: 'RASASI', categoria: 'Hombre', descripcion: 'Acuático helado fresco. Muy refrescante con cítricos, menta y ambroxan limpio.', notas_olfativas: ['Acuático', 'Cítrico', 'Almizcado'], ml: 100, precio_referencial: 98999, imagen: '/perfumes/hawas-ice.webp', link_whatsapp: wa('Hawas Ice') },
  { id: '37', nombre: 'Hawas Black', marca: 'RASASI', categoria: 'Hombre', descripcion: 'Dulce oscuro acuático. Perfil seductor con frescura especiada y fondo ambarado.', notas_olfativas: ['Acuático', 'Especiado', 'Ámbar'], ml: 100, precio_referencial: 73999, imagen: '/perfumes/hawas-black.webp', link_whatsapp: wa('Hawas Black') },
  { id: '38', nombre: 'Rasasi Hawas for Him', marca: 'RASASI', categoria: 'Hombre', descripcion: 'Acuático frutal masculino. Fresco, sexy y juvenil con canela, frutas y ambroxan.', notas_olfativas: ['Acuático', 'Frutal', 'Especiado'], ml: 100, precio_referencial: 63999, imagen: '/perfumes/rasasi-hawas-for-him.webp', link_whatsapp: wa('Rasasi Hawas for Him') },
  { id: '39', nombre: '9PM Elixir', marca: 'AFNAN', categoria: 'Hombre', descripcion: 'Vainillado especiado intenso. Dulce nocturno con frutas oscuras y fondo cremoso.', notas_olfativas: ['Vainilla', 'Especiado', 'Frutal'], ml: 100, precio_referencial: 111999, imagen: '/perfumes/9pm-elixir.webp', link_whatsapp: wa('9PM Elixir') },
  { id: '40', nombre: '9PM', marca: 'AFNAN', categoria: 'Hombre', descripcion: 'Dulce avainillado juvenil. Manzana, vainilla y ámbar con estilo seductor de noche.', notas_olfativas: ['Dulce', 'Vainilla', 'Ámbar'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/9pm.webp', link_whatsapp: wa('9PM') },
  { id: '42', nombre: 'Al Haramain Gold Edition', marca: 'AL HARAMAIN', categoria: 'Unisex', descripcion: 'Frutal oriental lujoso. Dulce refinado con frutas tropicales, almizcle y vainilla.', notas_olfativas: ['Frutal', 'Almizcado', 'Vainilla'], ml: 120, precio_referencial: 124999, imagen: '/perfumes/al-haramain-gold-edition-120ml.webp', link_whatsapp: wa('Al Haramain Gold Edition') },
  { id: '45', nombre: 'Ameerat al Arab', marca: 'ASDAAF', categoria: 'Mujer', descripcion: 'Floral oriental elegante. Jazmín, almizcle y vainilla con aire árabe refinado.', notas_olfativas: ['Floral', 'Almizcado', 'Vainilla'], ml: 100, precio_referencial: 69999, imagen: '/perfumes/ameerat-al-arab.webp', link_whatsapp: wa('Ameerat al Arab') },
  { id: '46', nombre: 'Bharara King', marca: 'BHARARA', categoria: 'Hombre', descripcion: 'Frutal tropical almizclado. Muy vibrante y potente con frutas exóticas y fondo limpio.', notas_olfativas: ['Frutal', 'Tropical', 'Almizcado'], ml: 100, precio_referencial: 119999, imagen: '/perfumes/bharara-king-edp-100ml.webp', link_whatsapp: wa('Bharara King') },
  { id: '47', nombre: 'Liquid Brun', marca: 'FRENCH AVENUE', categoria: 'Hombre', descripcion: 'Amaderado gourmand elegante. Vainilla tostada, cacao y maderas cálidas con sensación premium.', notas_olfativas: ['Amaderado', 'Vainilla', 'Gourmand'], ml: 100, precio_referencial: 99999, imagen: '/perfumes/liquid-brun.webp', link_whatsapp: wa('Liquid Brun') },
  { id: '48', nombre: 'Khamrah Dukhan', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Ámbar especiado, cálido y ahumado. Apertura intensa con especias orientales, corazón dulce y fondo amaderado con un carácter profundo y envolvente.', notas_olfativas: ['Ámbar', 'Especiado', 'Ahumado'], ml: 100, precio_referencial: 55999, imagen: '/perfumes/khamrah-dukhan.webp', link_whatsapp: wa('Khamrah Dukhan') },
  { id: '49', nombre: 'Spectre Ghost', marca: 'FRENCH AVENUE', categoria: 'Hombre', descripcion: 'Amaderado vainillado, elegante y misterioso. Salida aromática fresca, corazón especiado y fondo cremoso de vainilla y maderas nobles.', notas_olfativas: ['Amaderado', 'Vainilla', 'Especiado'], ml: 80, precio_referencial: 81999, imagen: '/perfumes/spectre-ghost.webp', link_whatsapp: wa('Spectre Ghost') },
  { id: '50', nombre: 'Art of Universe', marca: 'LATTAFA PRIDE', categoria: 'Unisex', descripcion: 'Frutal ambarado, moderno y refinado. Salida vibrante y fresca, corazón aromático y fondo cálido con matices amaderados.', notas_olfativas: ['Frutal', 'Ámbar', 'Amaderado'], ml: 100, precio_referencial: 71999, imagen: '/perfumes/art-of-universe.webp', link_whatsapp: wa('Art of Universe') },
  { id: '51', nombre: 'Hawas Fire', marca: 'RASASI', categoria: 'Hombre', descripcion: 'Aromático especiado, intenso y seductor. Cítricos luminosos, corazón especiado y fondo ambarado con gran presencia.', notas_olfativas: ['Aromático', 'Especiado', 'Ámbar'], ml: 100, precio_referencial: 94999, imagen: '/perfumes/hawas-fire.webp', link_whatsapp: wa('Hawas Fire') },
  { id: '52', nombre: 'Pisa', marca: 'LATTAFA PRIDE', categoria: 'Hombre', descripcion: 'Cítrico amaderado, fresco y sofisticado. Apertura luminosa, corazón aromático y fondo cálido con maderas elegantes.', notas_olfativas: ['Cítrico', 'Amaderado', 'Aromático'], ml: 100, precio_referencial: 80999, imagen: '/perfumes/pisa.webp', link_whatsapp: wa('Pisa') },
  { id: '53', nombre: 'Teriaq Intense', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Ámbar gourmand, dulce y cautivador. Salida especiada, corazón floral y fondo cremoso de vainilla y resinas orientales.', notas_olfativas: ['Ámbar', 'Gourmand', 'Vainilla'], ml: 100, precio_referencial: 65999, imagen: '/perfumes/teriaq-intense.webp', link_whatsapp: wa('Teriaq Intense') },
  { id: '54', nombre: 'Sehr', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Oriental gourmand, cálido y envolvente. Notas dulces y especiadas se funden sobre un fondo avainillado con aire lujoso.', notas_olfativas: ['Gourmand', 'Vainilla', 'Ámbar'], ml: 100, precio_referencial: 66999, imagen: '/perfumes/sehr.webp', link_whatsapp: wa('Sehr') },
  { id: '55', nombre: 'Vulcan Feu', marca: 'FRENCH AVENUE', categoria: 'Unisex', descripcion: 'Amaderado ahumado, poderoso y elegante. Salida especiada, corazón intenso y fondo profundo con maderas oscuras y notas cálidas.', notas_olfativas: ['Amaderado', 'Ahumado', 'Especiado'], ml: 100, precio_referencial: 86999, imagen: '/perfumes/vulcan-feu.webp', link_whatsapp: wa('Vulcan Feu') },
  { id: '56', nombre: 'Club de Nuit Precieux', marca: 'ARMAF', categoria: 'Hombre', descripcion: 'Frutal amaderado, refinado y vibrante. Salida fresca y afrutada, corazón elegante y fondo ambarado con gran proyección.', notas_olfativas: ['Frutal', 'Amaderado', 'Ámbar'], ml: 55, precio_referencial: 100999, imagen: '/perfumes/club-de-nuit-precieux.webp', link_whatsapp: wa('Club de Nuit Precieux') },
  { id: '57', nombre: 'Angham', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Floral gourmand, delicado y adictivo. Flores suaves, notas cremosas y un fondo cálido de vainilla y almizcle.', notas_olfativas: ['Floral', 'Gourmand', 'Almizcado'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/angham.webp', link_whatsapp: wa('Angham') },
  { id: '58', nombre: 'Ishq Al Shuyukh Gold', marca: 'LATTAFA PRIDE', categoria: 'Unisex', descripcion: 'Ámbar vainillado, seductor y cálido. Salida suave, corazón dulce y fondo cremoso con un carácter sofisticado.', notas_olfativas: ['Ámbar', 'Vainilla', 'Dulce'], ml: 100, precio_referencial: 59999, imagen: '/perfumes/ishq-al-shuyukh-gold.webp', link_whatsapp: wa('Ishq Al Shuyukh Gold') },
  { id: '59', nombre: 'Ishq Al Shuyukh Silver', marca: 'LATTAFA PRIDE', categoria: 'Unisex', descripcion: 'Fresco amaderado, limpio y versátil. Cítricos brillantes, corazón aromático y fondo almizclado con elegancia contemporánea.', notas_olfativas: ['Cítrico', 'Amaderado', 'Almizcado'], ml: 100, precio_referencial: 97999, imagen: '/perfumes/ishq-al-shuyukh-silver.webp', link_whatsapp: wa('Ishq Al Shuyukh Silver') },
  { id: '60', nombre: 'Oud For Glory', marca: 'LATTAFA', categoria: 'Unisex', descripcion: 'Amaderado oriental, intenso y majestuoso. Apertura especiada con azafrán y nuez moscada, corazón profundo de oud y fondo cálido con matices ambarados y almizclados.', notas_olfativas: ['Oud', 'Especiado', 'Ámbar'], ml: 100, precio_referencial: 64999, imagen: '/perfumes/oud-for-glory.webp', link_whatsapp: wa('Oud For Glory') },
]

export const products: Product[] = rawProducts.map((p) => ({
  ...p,
  slug: p.imagen.replace('/perfumes/', '').replace(/\.webp$/, ''),
}))

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
